backend:
  name: github
  repo: yourusername/your-repo-name   # ← Replace with your GitHub repo
  branch: main                        # ← Your default branch (usually "main" or "master")

media_folder: "gallery"               # Where uploaded images go
public_folder: "/gallery"             # URL path to access them

collections:
  - name: "gallery"
    label: "Photo Gallery"
    folder: "gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Caption", name: "caption", widget: "string"}